# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 15:48
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170817_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
