# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 15:57
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170818_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
